sudo: false
language: node_js
env:
  secure: gh/dkawNikAVt8nVYyLsJu8QqJaO83p0qdrZoakaVYeB9bLpdbWexL/j0moeTUsTjc4N5CVYsZdbcaVbq+OkeoQJ+JRjvAs3MjCPGEGXA0RM10NXSh0h0LUwlcwzYOQ/tVQ6ggD2J1sTZj8nr9FWFlbhXKrB9OawG1kZSohQ/hwVPsv6BONKnLFq7XEpclhfWqemUGb+UWqv5PfjQrSb1fCnkSUmsoMjkrNpvYPXzrpfxWPrM2CPJWYh8IyhkMoAXzWDqW1dS/TAhzA3DnfaVRxhDvPS+l9f84ICQVIthRUMwEyMOUiNLPLUXL4n7WciLFC9mgBAckKr2sf2AMfgkfvtPG3Npji/qMOBukDjTCa42qAdRiqmSreYyRimHwgjiBgcjytJOC7erLPIHGxUvLkU1dwDlHC+8p2AZ5efoovUVaZdJcJDRt8luHSkCknVB+vr0Pq94MJEtJvUmh8RPkqfQ0emQc+5nfq9qJo0+U1UweU7tnyh4X+Gm0+WMd+RJ/BMM/nAxeZybt/370JyYRiwhVk9Wrct14jSDFWxiz3njzV0+sMGRq5uPjij+iHGI8tH2zJljswh15vijpHofoDFenG5GJOIplWXsXKUyPQnpGzK3Rxrh7nm82No/v9JePYAMqvK3p8s+KqFC61Bm1d8rv5nEgBA9RkTpXtGRVs=
services:
- mysql
node_js:
- 13.14.0
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- mysql -e 'CREATE DATABASE test;'
install:
- npm ci
- npm install sharp
before_script:
- npm install -g sequelize-cli
- sequelize db:migrate
script:
- npm run test npm run jest
notification: email:false
