sudo: false
language: node_js
env:
  secure: U+IBm1F+kWLj5Z0gz4XET5yT80a0KjdQ9SVtjcNyMIDKQQZteaattjQRpuaTOt5O2J0mWJOFB94kQ7cpjjMHQyv8W74ia9pnEZytZfG7hXFjQFjiklmvJjMO3x3TAvFqb83ghjOxTyEdUuymGLDjsOaGXyAM8XHPbVmgQ9V6PFmlOmID9vSXLZ7CiCrpRjCODj4xJWR0pSuBdYJCrB+HoomZBFhg9ylOzv/se8no1PPV09f5bQG0uow62UVHRpsnpCiocqU3uGLX3tqvTITFMKPoGlIL8eYwToSgICJ65q5ncww7v+IUoRiokxQE+q0OxFSmPgLlb4f3x56AZfuSAWFNyExQGK5fjlw1dknQ/LaC4N4dGck+WCR27NjdBZuyRJVGE+gKwKHZyQUPfJB12o9DLj3xFtm2Ab7rS5Cw6zN367VVzBfNWRr4UmnK0YKfg/jXfsQbGlc9OMg14Wm7bUPbdxhSZh1CS9DjLOHS2FtjJov1ci1/wWyX9ULgji2b9iU5LM0IX0umySpSkPGsYaHpBnVsiWxJR242bFatETQJzt1vh7Z2ocmQiFqxAao0TQBijjYyur0k/pKFVIdQhka8CntamHW2zUC1WJbgHJKJPbj5LhgbwmIqXuh3MV08ip7/yIh4TuL0IH6xQWtGO/LyipJ4ZJI8W8Xe1bN5OcE=
services:
- mysql
node_js:
- 13.14.0
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- mysql -e 'CREATE DATABASE test;'
install:
- npm ci
- npm install sharp
before_script:
- npm install -g sequelize-cli
- sequelize db:migrate
script:
- npm run test npm run jest
notification: email:false
